<a href="https://colab.research.google.com/github/kostfere/code_snippets/blob/dev/multi_dimension_mulipliers.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
import pandas as pd
from scipy import optimize

In [0]:
nr_mults = np.random.randint(low=3, high=5)
dims_per_mult = np.random.randint(low=2, high=3, size=nr_mults)

In [0]:
muls=list()
dims=list()
for mul in range(0,nr_mults):
    for dim in range(0,dims_per_mult[mul]):
        muls.append('mul_'+str(mul))
        dims.append('dim_'+str(dim))
df = pd.DataFrame(data = {'muls': muls,
                         'dims': dims}
                  , columns=['muls','dims'])
#df = df[['muls','dims']]
df['code'] = ['w['+str(i)+']' for i in range(0,len(df))]

uniq_mults =np.unique(df.muls)

df_fin = df[df.muls==uniq_mults[0]][['code']].rename(columns={'code':'code_'+uniq_mults[0]})
df_fin.loc[:, 'dummy_var']=1;
for mul in uniq_mults[1:]:
    df_temp=df[df.muls==mul][['code']].rename(columns={'code':'code_'+mul})
    df_temp.loc[:, 'dummy_var']=1
    df_fin = df_fin.merge(df_temp,on = 'dummy_var')
df_fin = df_fin.drop('dummy_var',axis=1)
df_fin.loc[:, 'prod_format'] = df_fin.apply(lambda row: '*'.join(map(str, row.values)), axis=1)
k_values_str = np.random.uniform(0,2,size=len(df_fin))+2
df_fin.loc[:, 'k_values'] = k_values_str

In [0]:
expression = '' 
for i in range(0,len(df_fin)):
    expression+= 'np.abs(('+df_fin.loc[i].prod_format+'-'+str(df_fin.loc[i].k_values)+')/'+str(df_fin.loc[i].k_values)+')+'
expression = expression[:-1]
#expression

In [0]:
obj_fun_str =  """def obj_fun(w):
    return {}""".format(expression)

In [0]:
exec(obj_fun_str)

In [0]:
bnds = ((0.000001, 10000),)*len(df)
solution = optimize.minimize(obj_fun,np.ones(len(df)), bounds=bnds)
w = solution.x
#solution

In [0]:
df.loc[:, 'result'] = w
df_fin.loc[:, 'resulted_values'] = df_fin['prod_format'].apply(lambda row: eval(row))

In [9]:
df

    muls   dims  code    result
0  mul_0  dim_0  w[0]  1.521168
1  mul_0  dim_1  w[1]  1.386840
2  mul_1  dim_0  w[2]  1.569741
3  mul_1  dim_1  w[3]  1.340394
4  mul_2  dim_0  w[4]  1.580785
5  mul_2  dim_1  w[5]  1.330069

In [13]:
df_fin

  code_mul_0 code_mul_1 code_mul_2     prod_format  k_values  resulted_values
0       w[0]       w[2]       w[4]  w[0]*w[2]*w[4]  3.774660         3.774660
1       w[0]       w[2]       w[5]  w[0]*w[2]*w[5]  3.341114         3.175990
2       w[0]       w[3]       w[4]  w[0]*w[3]*w[4]  3.849679         3.223165
3       w[0]       w[3]       w[5]  w[0]*w[3]*w[5]  2.602035         2.711964
4       w[1]       w[2]       w[4]  w[1]*w[2]*w[4]  3.135117         3.441337
5       w[1]       w[2]       w[5]  w[1]*w[2]*w[5]  3.354815         2.895534
6       w[1]       w[3]       w[4]  w[1]*w[3]*w[4]  3.551121         2.938542
7       w[1]       w[3]       w[5]  w[1]*w[3]*w[5]  2.315149         2.472483